[tool.ruff]
# https://docs.astral.sh/ruff/settings/

# Target Python version
target-version = "py313" # change to match your Django project's Python version

# Exclude migrations from strict linting
exclude = [
  "**/migrations/**",
]

# Max line length (optional)
line-length = 99

# Enable autofix on save
fix = true

# Optional: Restrict to specific paths (e.g., Django apps)
# extend-include = ["*.py"]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
# Include common linting rules and Django-specific rules
select = [
  "E", # pycodestyle errors
  "F", # pyflakes
  "I", # isort (import sorting)
  "DJ", # Django-specific rules
  "D", # pydocstyle (docstring checks)
  "B", # flake8-bugbear
  "N", # pep8-naming
  "UP", # pyupgrade
]

# Docstring convention
[tool.ruff.lint.pydocstyle]
convention = "google" # or "numpy", "pep257"

[tool.black]
# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
# ^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
/(^/foo.py|migrations)/
'''
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
# reportOptionalMemberAccess = false
exclude = [
  "**/node_modules",
  "**/__pycache__",
  ".git",
  "app",
]
include = ["scripts", "server"]

[tool.django-stubs]
# django_settings_module = "config.settings"
