
[tool.black]
# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
# ^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
/(^/foo.py|migrations)/
'''
skip-string-normalization = true


[tool.isort]
profile = "black"


[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
# reportOptionalMemberAccess = false
include = ["scripts", "server"]
exclude = [
	"**/node_modules",
	"**/__pycache__",
	".git",
	"app",
]


[tool.django-stubs]
# django_settings_module = "config.settings"
